version: '3'

services:

  postgres:
    image: postgres:latest
    restart: always
    volumes: 
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    image: jboss/keycloak
    restart: always
    links:
      - postgres
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER : admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password